### ISSUE TITLE
POST "http://localhost:3000/api/words/" should have duplicate verification.

### ISSUE THREAD

**Issue by eamon0989** [alexandria-reader/backend#93]
If for some reason the words in text are not sent correctly from the server, trying to add a 'new' word results in a unique violation. Maybe a check could be added, and if the word already exists, it will just add the translation?

**Comment by mrchrmn** [comment]
This may actually be a bug. Can you describe the process in a bit more detail? What exactly is being sent from the client? And what is the actual unique violation?

**Comment by eamon0989** [comment]
Here are the logs:

```
Dec 29 2021 12:04:32 SELECT * FROM users WHERE id = '6'
Dec 29 2021 12:04:32 
      SELECT * FROM texts
       WHERE user_id = '6' AND language_id = 'fr'
    ORDER BY last_opened DESC NULLS LAST
Dec 29 2021 12:04:41 SELECT * FROM users WHERE id = '6'
Dec 29 2021 12:04:42 
    SELECT * FROM words 
     WHERE language_id = 'fr' 
           AND 
           word = 'personnes'
Dec 29 2021 12:04:42 
    INSERT INTO users_words (user_id, word_id, word_status)
         VALUES (6, 11, 'learning')
      RETURNING *
duplicate key value violates unique constraint "users_words_pkey"
```

Sometimes (due to errors on the frontend) the user words are not correctly loaded. So when a user trys to add a translation to a word that already exists in the database, the above mentioned route tries to add a new word without checking if the word already exists in the database.

**Comment by mrchrmn** [comment]
That's not quite the case: The check is done. That's why no new word is being inserted, and there is only the `SELECT` query on the `words` table. The problem lies with entering the existing word into the `users_words` table, where the entry already exists - user 6 has previously already marked word 11 as 'learning'. It seems I also have to make a check there as well to get out of this situation gracefully.
